algoritmo "Descobre se a>=b"
// Função :Descobre se a>=b
// Autor :Leonardo Faria Araujo
// Data : 07/04/2020
// Seção de Declarações 
var
a, b: inteiro
c: logico
inicio
// Seção de Comandos 

Escreva ("Entre com o valor da variavel A: ")
Leia(a)

Escreva("Entre com o valor B: ")
Leia(b)

Se (a >= b) Entao
C <- VERDADEIRO
SENAO
C<- FALSO
fimse

Escreva ("Valor Logico armazenado na variavel C:", C)


fimalgoritmo
