algoritmo "semnome"
// Função :
// Autor :
// Data : 07/04/2020
// Seção de Declarações 
var

np : numerico
vt : numerico

inicio
// Seção de Comandos 

escreva("Entre com o numero de peças vendidas:")
Leia(np)

SE(np >= 1000) Entao
Escreva("Valor Total Comissão: ", np * 7)
fimse
Se(np >= 500) e (np <1000) Entao
escreva("Valor total comissão: ", np * 5)
fimse
se(np < 500) entao
Escreva("Valor total comissão:", np * 3)
fimse


fimalgoritmo
